In [1]:
import numpy as np
import matplotlib.pyplot as plt



In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

인덱싱과 슬라이싱

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능


-1차원 벡터 인덱싱


In [3]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[3]
x

3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 2차원 벡터 인덱싱


In [5]:
x=np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x[0,2]

2

In [7]:
x[0]

array([0, 1, 2, 3, 4])

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능


- 1차원 벡터 슬라이싱


In [13]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x=np.arange(10).reshape(2,5)
x


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
x[0,:2]


array([0, 1])

In [18]:
x[:1,:2]


array([[0, 1]])

In [19]:
x[:1,2]

array([2])

## ndarray shape 변경하기
#### ravel, np.ravel
    - 다차원배열을 1차원으로 변경
    - 'order' 파라미터
        - 'C' - row 우선 변경
        - 'F - column 우선 변경
    - 원본을 참조 함

In [16]:
x = np.arange(15).reshape(3, 5)
print(x)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
np.ravel(x,order="F")   # 열우선 배치

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [18]:
np.ravel(x,order="C")  # 행우선 배치--기본 설정값


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
# 원본을 참조함
temp=x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
# temp나 x변수 모두 동일한 주소를 참조(즉 temp의 원소를 변경하면 원본x의 원소도 변경된다.)
temp[0]=100
temp
x


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [26]:
# 보통은 array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
#         13,  14])
# 두다가 array([[100,   1,   2,   3,   4],
#              [  5,   6,   7,   8,   9],
#               [ 10,  11,  12,  13,  14]])
# 이리 둔다


#### flatten
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점: copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
 (값을 변경하고자 할때는 shape대신 flatten을 사용한다.
 
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경


In [27]:
y=np.arange(15).reshape(3,5)
print(y)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [28]:
t2=y.flatten(order='F')
t2



array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [29]:
t2[0]
t2
y



0

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

    

reshape 함수는 이미지 데이터를 조정할떄에 자주 쓰임.
이미지 데이터는 보통 2차원이나 3차원인데 1차원 데이터로 바꾸어서 고친다.

In [8]:
x=np.arange(36)
print(x)
print(x.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)


In [9]:
y= x.reshape(6,6)
y
y.shape
y.ndim


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

(6, 6)

2

In [10]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [32]:
# k=x.reshape(3,3,-1)

##  헹을 결정하고 열을 -1로 주면 원소의 개수에 따라 열 개수가 정해진다.


# k=x.reshape(3,-1,2)
##  열을 결정하고(2로) 행을 -1로 주면 원소의 개수에 따라 행 개수가 정해진다.

In [11]:
k=x.reshape(3,3,-1) # 행을 결정하고 열을 -1 로 주면 원소의 개수에 따라 열 개수가 정해짐
k
k.shape
k.ndim


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

(3, 3, 4)

3

In [12]:
k=x.reshape(3,-1,3) # 행을 결정하고 열을 -1 로 주면 원소의 개수에 따라 열 개수가 정해짐
k
k.shape
k.ndim


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

(3, 4, 3)

3

In [13]:

x_1 = np.arange(35)
x_1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [14]:
x_1.reshape(3,3,4) #cannot reshape array of size 35 into shape (3,3,4)
# cannot reshape array of size 35 into shape (3,3,4)>>원소의 숫자가 36개여야 하나 하나부족

ValueError: cannot reshape array of size 35 into shape (3,3,4)

In [15]:
x_1.reshape(3,2,2) #cannot reshape array of size 35 into shape (3,2,2)
cannot reshape array of size 35 into shape (3,2,2)>1개원소..

ValueError: cannot reshape array of size 35 into shape (3,2,2)