In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서


In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.70736286 0.31278618 0.14447129 0.84514443 0.07086799]
 [0.93752906 0.42250787 0.19176404 0.91713603 0.09916564]
 [0.12082238 0.4966848  0.23886927 0.80158678 0.75831119]]


#### 연산 함수
 - add, subtract, multiply, divide

    

In [8]:
np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)

array([[ 0.70816909,  1.28838299,  2.11515997,  3.3356081 ,  4.82278998],
       [ 5.6183197 ,  6.48957862,  7.22355201,  8.52493795,  9.87830335],
       [10.50692684, 11.3667214 , 12.50866712, 13.58838609, 14.15295851]])

array([[-0.70816909,  0.71161701,  1.88484003,  2.6643919 ,  3.17721002],
       [ 4.3816803 ,  5.51042138,  6.77644799,  7.47506205,  8.12169665],
       [ 9.49307316, 10.6332786 , 11.49133288, 12.41161391, 13.84704149]])

array([[0.        , 0.28838299, 0.23031995, 1.0068243 , 3.29115992],
       [3.09159851, 2.93747169, 1.5648641 , 4.19950363, 7.90473015],
       [5.06926839, 4.03393535, 6.10400543, 7.64901918, 2.14141909]])

array([[ 0.        ,  3.46761094, 17.36714522,  8.93899761,  4.86150791],
       [ 8.08643163, 12.25543725, 31.31262321, 15.23989635, 10.24702912],
       [19.72671246, 29.99552286, 23.59106682, 22.09433601, 91.52809017]])

In [10]:
x+y
x-y
x*y
x%y


array([[ 0.70816909,  1.28838299,  2.11515997,  3.3356081 ,  4.82278998],
       [ 5.6183197 ,  6.48957862,  7.22355201,  8.52493795,  9.87830335],
       [10.50692684, 11.3667214 , 12.50866712, 13.58838609, 14.15295851]])

array([[-0.70816909,  0.71161701,  1.88484003,  2.6643919 ,  3.17721002],
       [ 4.3816803 ,  5.51042138,  6.77644799,  7.47506205,  8.12169665],
       [ 9.49307316, 10.6332786 , 11.49133288, 12.41161391, 13.84704149]])

array([[0.        , 0.28838299, 0.23031995, 1.0068243 , 3.29115992],
       [3.09159851, 2.93747169, 1.5648641 , 4.19950363, 7.90473015],
       [5.06926839, 4.03393535, 6.10400543, 7.64901918, 2.14141909]])

array([[0.        , 0.13485104, 0.04228043, 0.3151352 , 0.70884008],
       [0.05344238, 0.12505662, 0.06988755, 0.1259307 , 0.2169665 ],
       [0.36839005, 0.36507953, 0.30065626, 0.055506  , 0.08077588]])

    통계 함수
        - 평균,분산.중앙.최대값,최소값 등등 통계 관련된 함수가 내장
    

In [12]:
y



array([[0.70816909, 0.28838299, 0.11515997, 0.3356081 , 0.82278998],
       [0.6183197 , 0.48957862, 0.22355201, 0.52493795, 0.87830335],
       [0.50692684, 0.3667214 , 0.50866712, 0.58838609, 0.15295851]])

In [13]:
y.mean()  #평균
y.max()   # 최대
y.min()   # 최소


0.4752307814624127

0.8783033497929275

0.11515997448946735

In [14]:
np.var(y)  #분산
np.median(y) #중간값
np.std(y)    #표준변차


0.04924243267819259

0.5069268393287971

0.2219063601571451

#### 집계함수
- sum: 합계, cumsum:누적합계
        

In [16]:
x



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
np.sum(x, axis=None)     # 전체 원소의 합계
np.sum(x, axis=0)        # 각 열의 합계
np.sum(x, axis=1)        # 각 행의 합계
np.sum(x)


105

array([15, 18, 21, 24, 27])

array([10, 35, 60])

105

In [21]:
np.cumsum(x)



array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105], dtype=int32)

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False


In [23]:
z=np.random.randn(10)

z


array([-0.70375524, -1.19031722,  1.79567031, -1.2208012 , -0.11346352,
        0.06560469, -0.66171888,  1.18895702,  0.2247256 , -1.9158655 ])

In [24]:
z>0


array([False, False,  True, False, False,  True, False,  True,  True,
       False])

In [26]:
np.any(z>0)         #z의 원소중 0초과하는 값이 1개라도 존재하면 True


True

In [27]:
np.all(z>0)    # z의 원소 모두가 0초과하는 값이면 True


False

In [28]:
np.all(z !=0)


True

#### where(조건,조건이 참인경우,조건이 거짓인 경우) 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우




In [30]:
z=np.random.randn(10)

z


array([ 1.28839761,  2.00526576,  0.65241859,  0.9323967 , -1.2658337 ,
        0.59385435,  1.97186565,  1.3715456 , -1.53410057, -1.36907953])

In [31]:
np.where(z>0,z,0)


array([1.28839761, 2.00526576, 0.65241859, 0.9323967 , 0.        ,
       0.59385435, 1.97186565, 1.3715456 , 0.        , 0.        ])

In [32]:
np.where(z>0,10,0)


array([10, 10, 10, 10,  0, 10, 10, 10,  0,  0])

# axis 파라미터 이해


#### axis 이해하기
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용


* axis를 파라미터로 갖는 함수를 이용하기
 - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
 - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 **따라서** 연산이 적용
   - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
 - 예) np.sum, np.mean, np.any 등등


In [33]:
x=np.arange(15)
print(x)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


- 1차원 데이터 적용


In [34]:
np.sum(x,axis=0)


105

In [35]:
np.sum(x,axis=1)  # axis 1 is out of bounds for array of dimension 1    에러~!


AxisError: axis 1 is out of bounds for array of dimension 1

- 행렬에 적용(2차원 데이터)


In [36]:
y=x.reshape(3,5)
y



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:

np.sum(y, axis=0)        # 각 열의 합계
np.sum(y, axis=1)        # 각 행의 합계
np.sum(y, axis=2)        # axis 2 is out of bounds for array of dimension 2-에러


array([15, 18, 21, 24, 27])

array([10, 35, 60])

AxisError: axis 2 is out of bounds for array of dimension 2

-3차원 텐서에 적용하기


In [39]:
nums = np.array(
    [[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]
)
nums

nums.ndim             # >3이라고 나왔으니 3차원


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

3

In [43]:
np.sum(nums, axis=0)        



array([[ 6,  8, 10],
       [12, 14, 16]])

In [44]:
np.sum(nums, axis=1)        

array([[ 3,  5,  7],
       [15, 17, 19]])

In [45]:
np.sum(nums, axis=2)   

array([[ 3, 12],
       [21, 30]])